routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

//Route::get('/',             ['as' => 'home',        'uses' => 'HomeController@index']);
//Route::get('/login',        ['as' => 'login',       'uses' => 'LoginController@index']);
//Route::get('/menu',         ['as' => 'menu',        'uses' => 'MenuController@index']);
//Route::get('/order',        ['as' => 'order',       'uses' => 'OrderController@index']);
//Route::get('/orders',       ['as' => 'orders',      'uses' => 'OrderController@orders']);
//Route::get('/user',         ['as' => 'user',        'uses' => 'UserController@orders']);


// Rotas da Api

Route::group(['prefix' => 'api','as' => 'api.','middleware' => ['api']],function(){

    Route::group(['prefix' => 'cart','as' => 'cart.'],function(){

        Route::post('add',              ['uses' => 'Api\CartController@add',            'as' => 'add']);
        Route::post('del',              ['uses' => 'Api\CartController@del',            'as' => 'del']);
    });
});

// Rotas do Site

Route::group(['middleware' => ['cart']],function(){

    Route::get('/',['uses' => 'HomeController@index', 'as' => 'index']);

    Route::get('/home',function(){

        return redirect()->route('index');
    });

    Route::get('/login',function(){

        return redirect()->route('user.login.form');
    });

    Route::get('/logout',function(){

        return redirect()->route('user.logout');
    });

    // Products

    Route::group(['prefix' => 'product','as' => 'product.'],function(){

        Route::get('/',                     ['uses' => 'ProductController@index',           'as' => 'index']);
    });

    Route::group(['prefix' => 'order','as' => 'order.','middleware' => 'auth'],function(){

        Route::get('/',                     ['uses' => 'OrderController@index',             'as' => 'index']);
        Route::post('store',                ['uses' => 'OrderController@store',             'as' => 'store']);
        Route::get('history',               ['uses' => 'OrderController@history',           'as' => 'history']);
        Route::get('{id}',                  ['uses' => 'OrderController@show',              'as' => 'show']);
    });

    Route::group(['prefix' => 'user','as' => 'user.'],function(){

        Route::group(['prefix' => 'login','as' => 'login.'],function(){

            Route::get('/',                 ['uses' => 'UserController@login',                              'as' => 'form']);
            Route::post('/',                ['uses' => 'UserController@verify',                             'as' => 'verify']);
        });

        Route::post('store',                ['uses' => 'UserController@store',                              'as' => 'store']);
        Route::get('logout',                ['uses' => 'UserController@logout',                             'as' => 'logout']);
        Route::get('profile',               ['uses' => 'UserController@profile',                            'as' => 'profile']);
        Route::post('address',              ['uses' => 'UserController@address',                            'as' => 'add_address']);
        Route::post('{id}/update',          ['uses' => 'UserController@update',                             'as' => 'update']);

//        Route::group(['prefix' => 'user','as' => 'user.'],function(){
//
//            Route::get('siginup',               ['uses' => 'UserController@create',                             'as' => 'create']);
//            Route::post('siginup',              ['uses' => 'UserController@store',                              'as' => 'store']);
//            Route::post('login',                ['uses' => 'UserController@login',                              'as' => 'login']);
//            Route::get('logout',                ['uses' => 'UserController@logout',                             'as' => 'logout']);
//            Route::get('profile',               ['uses' => 'UserController@profile',                            'as' => 'profile']);
//            Route::post('address',              ['uses' => 'UserController@address',                            'as' => 'add_address']);
//            Route::post('{id}/update',          ['uses' => 'UserController@update',                             'as' => 'update']);
//
//        });



//        Route::post('siginup',              ['uses' => 'UserController@store',                              'as' => 'store']);
//
//        Route::get('logout',                ['uses' => 'UserController@logout',                             'as' => 'logout']);
//        Route::get('profile',               ['uses' => 'UserController@profile',                            'as' => 'profile']);
//        Route::post('address',              ['uses' => 'UserController@address',                            'as' => 'add_address']);
//        Route::post('{id}/update',          ['uses' => 'UserController@update',                             'as' => 'update']);

    });

    // Auth Routes

    Route::group(['prefix' => 'password','as' => 'password.'],function(){

        Route::get('email',                 ['uses' => 'Auth\ForgotPasswordController@showLinkRequestForm', 'as' => 'email']);
        Route::post('email',                ['uses' => 'Auth\ForgotPasswordController@sendResetLinkEmail',  'as' => 'email']);
        Route::get('reset/{token}',         ['uses' => 'Auth\ResetPasswordController@showResetForm',        'as' => 'reset']);
        Route::post('reset',                ['uses' => 'Auth\ResetPasswordController@reset',                'as' => 'reset']);
    });

});

// Rotas do Admin

Route::group(['prefix' => 'admin','as' => 'admin.'],function(){

    // Rotas de Login

    Route::get('login',                 ['uses' => 'Admin\AuthController@index',            'as' => 'login']);
    Route::post('login',                ['uses' => 'Admin\AuthController@login',            'as' => 'login']);


    Route::group(['middleware' => ['orders','admin']],function(){

        // Logout

        Route::get('logout',                ['uses' => 'Admin\AuthController@logout',               'as' => 'logout']);

        // Profile

        Route::get('profile',               ['uses' => 'Admin\AdminController@profile',             'as' => 'profile']);
        Route::post('profile',              ['uses' => 'Admin\AdminController@update_profile',      'as' => 'profile']);

        // Rota Principal

        Route::get('',                      ['uses' => 'Admin\HomeController@index',        'as' => 'index']);

        // Rota Produtos

        Route::group(['prefix' => 'product','as' => 'product.'],function(){

            Route::get('/',                 ['uses' => 'Admin\ProductController@index',         'as' => 'index']);
            Route::get('create',            ['uses' => 'Admin\ProductController@create',        'as' => 'create']);
            Route::post('store',            ['uses' => 'Admin\ProductController@store',         'as' => 'store']);
            Route::get('{id}/edit',         ['uses' => 'Admin\ProductController@edit',          'as' => 'edit']);
            Route::put('{id}',              ['uses' => 'Admin\ProductController@update',        'as' => 'update']);
            Route::delete('{id}',           ['uses' => 'Admin\ProductController@destroy',       'as' => 'destroy']);
        });

        // Rota Categorias

        Route::group(['prefix' => 'category','as' => 'category.'],function(){

            Route::get('/',                 ['uses' => 'Admin\CategoryController@index',    'as' => 'index']);
            Route::get('create',            ['uses' => 'Admin\CategoryController@create',   'as' => 'create']);
            Route::post('store',            ['uses' => 'Admin\CategoryController@store',    'as' => 'store']);
            Route::get('{id}/edit',         ['uses' => 'Admin\CategoryController@edit',     'as' => 'edit']);
            Route::delete('{id}',           ['uses' => 'Admin\CategoryController@destroy',  'as' => 'destroy']);
            Route::put('{id}',              ['uses' => 'Admin\CategoryController@update',   'as' => 'update']);
        });

        // Rota Clientes

        Route::group(['prefix' => 'user','as' => 'user.'],function() {
            Route::get('/',             ['uses' => 'Admin\UserController@index',    'as' => 'index']);
            Route::post('store',        ['uses' => 'Admin\UserController@store',    'as' => 'store']);
            Route::get('/{id}/edit',    ['uses' => 'Admin\UserController@edit',     'as' => 'edit']);
            Route::get('create',        ['uses' => 'Admin\UserController@create',   'as' => 'create']);
            Route::get('export',        ['uses' => 'Admin\UserController@export',   'as' => 'export']);
        });

        // Rota Pedidos

        Route::group(['prefix' => 'order','as' => 'order.'],function(){

            Route::get('/',                 ['uses' => 'Admin\OrderController@index',                   'as' => 'index']);
            Route::get('/create',           ['uses' => 'Admin\OrderController@create',                  'as' => 'create']);
            Route::post('/check',           ['uses' => 'Admin\OrderController@check',                   'as' => 'check']);
            Route::get('/{id}',             ['uses' => 'Admin\OrderController@show',                    'as' => 'show']);
            Route::put('/{id}',             ['uses' => 'Admin\OrderController@update',                  'as' => 'update']);
            Route::get('/{id}/{status}',    ['uses' => 'Admin\OrderController@update_order_status',     'as' => 'update_order_status']);
        });

        // Rota Entrega

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Product extends Model
{

    use SoftDeletes;

    protected $fillable = ['category_id','name','description','value','img'];

    protected $dates = [

        'created_at',
        'updated_at',
        'deleted_at'
    ];

    public function category(){

        return $this->belongsTo('App\Category');
    }

    public function order_items(){

        return $this->hasMany('App\OrderItem')->withTrashed();
    }
}

app/Http/Controllers/Admin/ProductController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Category;
use App\Product;
use App\Services\ProductService;
use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use App\Http\Requests\Admin\ProductStoreRequest;
use App\Http\Requests\Admin\ProductUpdateRequest;

class ProductController extends Controller
{

    private $product_service;

    public function __construct(){

        $this->product_service = new ProductService();
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $scripts = [

            asset('assets/admin/js/page/product.js')
        ];

        $data = $request->all();
        $products = $this->product_service->get_products($data);

        return view('admin.product.index')
            ->with('products',$products)
            ->with('scripts',$scripts);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {

        $scripts = [

            asset('assets/plugins/jquery-mask/jquery.mask.min.js'),
            asset('assets/admin/js/page/product_create.js')
        ];

        $categories = Category::pluck('name','id');

        return view('admin.product.create')
            ->with('scripts',$scripts)
            ->with('categories',$categories);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(ProductStoreRequest $request)
    {

        $data = $request->all();
        $product_store_response = $this->product_service->product_store($data);

        if($product_store_response['error']){

            return redirect()->back()->with('error',$product_store_response['msg']);
        }

        return redirect()->route('admin.product.index')->with('success',$product_store_response['msg']);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {

        $scripts = [

            asset('assets/plugins/jquery-mask/jquery.mask.min.js'),
            asset('assets/admin/js/page/product_update.js')
        ];

        $product = Product::find($id);

        $categories = Category::pluck('name','id');

        return view('admin.product.edit')
            ->with('product',$product)
            ->with('categories',$categories)
            ->with('scripts',$scripts);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(ProductUpdateRequest $request, $id)
    {
        $data = $request->all();
        $product_update_response = $this->product_service->product_update($data,$id);

        if($product_update_response['error']){

            return redirect()->back()->with('error',$product_update_response['msg']);
        }

        return redirect()->route('admin.product.index')->with('success',$product_update_response['msg']);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {

        $product_destroy_response = $this->product_service->product_destroy($id);

        if($product_destroy_response['error']){

            return redirect()->back()->with('error',$product_destroy_response['msg']);
        }

        return redirect()->route('admin.product.index')->with('success',$product_destroy_response['msg']);
    }
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use App\Product;
use Illuminate\Http\Request;

use App\Http\Requests;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {

        $dias_funcionamento = \Config::get('daikon.dias_funcionamento');
        $hora_funcionamento = \Config::get('daikon.hora_funcionamento');

        if(!in_array(date('N'),$dias_funcionamento) || date('H:i') < $hora_funcionamento['inicio'] || date('H:i') > $hora_funcionamento['fim']){

            return redirect()->route('index')->with('open_error','Fora do horário de funcionamento');
        }

        $categories = Category::orderBy('name','asc')
            ->get();

        $products_query = Product::select('*');

        if($request->has('category')){

            $products_query->where('category_id',$request->get('category'));
        }

        return view('product.index')
            ->with('categories',$categories);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/admin/product/create.blade.php
@extends('admin.layout')
@section('content')

<!-- conteúdo -->
<div class="limite content">
	<section class="form detalhes">
		<h2 class="clearfix">
			<i class="fa fa-cutlery styled"></i>
			Adicionar prato
		</h2>
		<div class="box meusdados">
			@include('includes._errors')
			{{ Form::open(['url' => route('admin.product.store'),'method' => 'POST','files' => true]) }}
			<ul>
				<li>
					{{ Form::label('Nome') }}
					{{ Form::text('name',null,['placeholder' => 'Inserir nome do produto']) }}
				</li>
				<li>
					{{ Form::label('Descrição (opcional)') }}
					{{ Form::text('description',null,['placeholder' => 'Inserir descrição do produto']) }}
				</li>
				<li>
					{{ Form::label('Valor unitário') }}
					{{ Form::text('value',null,['class' => 'money','placeholder' => 'R$ 00.00']) }}
				</li>
				<li>
					{{ Form::label('Selecione a Categoria') }}
					{{ Form::select('category_id',$categories) }}
				</li>
			</ul>
			<ul>
				<li>
					<div id="imgpreview">
						<img src="http://dummyimage.com/800x600/4d494d/686a82.gif&text=placeholder+image" alt="" />
					</div>
					<div class="carregar">
						<b class="botao">
							Carregar imagem
							{{ Form::file('image',['id' => 'image','accept' => 'image/*']) }}
						</b>
						<span>Selecione uma imagem</span>
					</div>
				</li>
			</ul>
			<div class="clearfix p-left-20 p-top-20">
				{{ Form::submit('Adicionar produto',['class' => 'botao']) }}
				<a href="{{ route('admin.product.index') }}" class="botao cancel">
					Cancelar
				</a>
			</div>
			{{ Form::close() }}
		</div>
	</section>
</div>
<script>
	$(function () {
		var $image = $('#image');
		var cropBoxData;
		var canvasData;

		$('#modal').on('shown.bs.modal', function () {
			$image.cropper({
				autoCropArea: 0.5,
				built: function () {
					$image.cropper('setCanvasData', canvasData);
					$image.cropper('setCropBoxData', cropBoxData);
				}
			});
		}).on('hidden.bs.modal', function () {
			cropBoxData = $image.cropper('getCropBoxData');
			canvasData = $image.cropper('getCanvasData');
			$image.cropper('destroy');
		});
	});
</script>
@endsection

resources/views/admin/product/edit.blade.php
@extends('admin.layout')
@section('content')

<!-- conteúdo -->
<div class="limite content">
	<section class="form detalhes">
		<h2 class="clearfix">
			<i class="fa fa-cutlery styled"></i>
			Editar prato
		</h2>
		@include('includes._errors')
		<div class="box meusdados">
			{{ Form::open(['url' => route('admin.product.update',$product->id),'method' => 'PUT','files' => true]) }}
			<ul>
				<li>
					{{ Form::label('Nome') }}
					{{ Form::text('name',$product->name,['placeholder' => 'Inserir nome do produto']) }}
				</li>
				<li>
					{{ Form::label('Descrição (opcional)') }}
					{{ Form::text('description',$product->description,['placeholder' => 'Inserir descrição do produto']) }}
				</li>
				<li>
					{{ Form::label('Valor unitário') }}
					{{ Form::text('value',number_format($product->value,2,'.',''),['placeholder' => 'R$ 00.00','class' => 'money']) }}
				</li>
				<li>
					{{ Form::label('Selecione a categoria') }}
					{{ Form::select('category_id',$categories,$product->category_id) }}
				</li>
			</ul>
			<ul>
				<li>
					<div id="imgpreview">
						<img src="{{ asset($product->img) }}" alt="" />
					</div>
					<div class="carregar">
						<b class="botao">
							Carregar imagem
							<input type="file" name="image" id="image" />
						</b>
						<span>Selecione uma imagem</span>
					</div>
				</li>
			</ul>
			<ul>
				<li>
					<input type="submit" class="botao" value="Salvar alterações">
					<a href="{{ route('admin.product.index') }}" class="botao cancel">
						Cancelar
					</a>
				</li>
			</ul>
			{{ Form::close() }}
			{{ Form::open(['url' => route('admin.product.destroy',$product->id),'id' => 'delete_product_' . $product->id,'method' => 'DELETE']) }}
			<div class="clearfix p-left-20 p-top-20">
				{{ Form::button('Remover produto',['class' => 'f-right botao delete']) }}
			</div>
			{{ Form::close() }}
		</div>
	</section>
</div>
<div class="confirmation-modal modal" tabindex="-1" role="dialog">
	<div class="">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
				<h4 class="modal-title">Confirmation required</h4>
			</div>
			<div class="modal-body">Are you sure you want to delete that comment?</div>
			<div class="modal-footer">
				<button class="confirm btn " type="button" data-dismiss="modal" data-href="">Excluir produto</button>
				<button class="cancel btn " type="button" data-dismiss="modal">Cancelar</button>
			</div>
		</div>
	</div>
</div>
@endsection

resources/views/admin/product/index.blade.php
@extends('admin.layout')
@section('content')
<!-- tabs - submenu -->
@include('admin.include.header_product')
<!-- conteúdo -->
<div class="limite content">
	<section class="tabela">
		<h2 class="clearfix">
			<i class="fa fa-cutlery styled"></i>
			Pratos no cardápio
			{{ Form::open(['name' => 'interval_form','method' => 'GET', 'url' => request()->url() ]) }}

			<div class="filter">
				Ordenar por:
				{{ Form::select('interval',['category' => 'Categoria','new' => 'Mais recentes','old' => 'Mais antigos','des_value' => 'Maior valor','asc_value' => 'Menor valor'],request()->has('interval') && request()->get('interval') != null ? request()->get('interval') : null) }}
			</div>

			{{ Form::close() }}

			<div class="pesquisa">
				{{ Form::open(['name' => 'search','method' => 'GET', request()->url()]) }}
				{{ Form::text('search',request()->get('search'),['placeholder' => 'Pesquisar']) }}
				{{ Form::close() }}
				<i class="fa fa-search"></i>
			</div>
			<a class="botao menor" href="{{ route('admin.product.create') }}"><i class="fa fa-plus-square-o"></i>Adicionar produto</a>
		</h2>
		@include('includes._errors')
		<table class="clicavel">
			<thead>
				<th>Nome</th>
				<th>Categoria</th>
				<th>Valor</th>
				<th>Cadastrado em</th>
			</thead>
			<tbody>
			@foreach($products as $product)
				<tr data-href='{{ route('admin.product.edit',$product->id) }}' title="Clique para ver os detalhes">
					<td>{{ sprintf('%02d', $product->id) }} - {{ $product->name }}</td>
					<td>{{ $product->category->name }}</td>
					<td>R$ {{ number_format($product->value,2,'.','') }}</td>
					<td>{{ $product->created_at->format('d/m/Y - H:i') }}</td>
				</tr>
			@endforeach
			</tbody>
		</table>
	</section>
	<nav class="pager">
		{{ $products->appends(['status' => request()->get('status'), 'interval' => request()->get('interval'), 'search' => request()->get('search') ])->links() }}
	</nav>
</div>
@endsection