routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

//Route::get('/',             ['as' => 'home',        'uses' => 'HomeController@index']);
//Route::get('/login',        ['as' => 'login',       'uses' => 'LoginController@index']);
//Route::get('/menu',         ['as' => 'menu',        'uses' => 'MenuController@index']);
//Route::get('/order',        ['as' => 'order',       'uses' => 'OrderController@index']);
//Route::get('/orders',       ['as' => 'orders',      'uses' => 'OrderController@orders']);
//Route::get('/user',         ['as' => 'user',        'uses' => 'UserController@orders']);


// Rotas da Api

Route::group(['prefix' => 'api','as' => 'api.','middleware' => ['api']],function(){

    Route::group(['prefix' => 'cart','as' => 'cart.'],function(){

        Route::post('add',              ['uses' => 'Api\CartController@add',            'as' => 'add']);
        Route::post('del',              ['uses' => 'Api\CartController@del',            'as' => 'del']);
    });
});

// Rotas do Site

Route::group(['middleware' => ['cart']],function(){

    Route::get('/',['uses' => 'HomeController@index', 'as' => 'index']);

    Route::get('/home',function(){

        return redirect()->route('index');
    });

    Route::get('/login',function(){

        return redirect()->route('user.login.form');
    });

    Route::get('/logout',function(){

        return redirect()->route('user.logout');
    });

    // Products

    Route::group(['prefix' => 'product','as' => 'product.'],function(){

        Route::get('/',                     ['uses' => 'ProductController@index',           'as' => 'index']);
    });

    Route::group(['prefix' => 'order','as' => 'order.','middleware' => 'auth'],function(){

        Route::get('/',                     ['uses' => 'OrderController@index',             'as' => 'index']);
        Route::post('store',                ['uses' => 'OrderController@store',             'as' => 'store']);
        Route::get('history',               ['uses' => 'OrderController@history',           'as' => 'history']);
        Route::get('{id}',                  ['uses' => 'OrderController@show',              'as' => 'show']);
    });

    Route::group(['prefix' => 'user','as' => 'user.'],function(){

        Route::group(['prefix' => 'login','as' => 'login.'],function(){

            Route::get('/',                 ['uses' => 'UserController@login',                              'as' => 'form']);
            Route::post('/',                ['uses' => 'UserController@verify',                             'as' => 'verify']);
        });

        Route::post('store',                ['uses' => 'UserController@store',                              'as' => 'store']);
        Route::get('logout',                ['uses' => 'UserController@logout',                             'as' => 'logout']);
        Route::get('profile',               ['uses' => 'UserController@profile',                            'as' => 'profile']);
        Route::post('address',              ['uses' => 'UserController@address',                            'as' => 'add_address']);
        Route::post('{id}/update',          ['uses' => 'UserController@update',                             'as' => 'update']);

//        Route::group(['prefix' => 'user','as' => 'user.'],function(){
//
//            Route::get('siginup',               ['uses' => 'UserController@create',                             'as' => 'create']);
//            Route::post('siginup',              ['uses' => 'UserController@store',                              'as' => 'store']);
//            Route::post('login',                ['uses' => 'UserController@login',                              'as' => 'login']);
//            Route::get('logout',                ['uses' => 'UserController@logout',                             'as' => 'logout']);
//            Route::get('profile',               ['uses' => 'UserController@profile',                            'as' => 'profile']);
//            Route::post('address',              ['uses' => 'UserController@address',                            'as' => 'add_address']);
//            Route::post('{id}/update',          ['uses' => 'UserController@update',                             'as' => 'update']);
//
//        });



//        Route::post('siginup',              ['uses' => 'UserController@store',                              'as' => 'store']);
//
//        Route::get('logout',                ['uses' => 'UserController@logout',                             'as' => 'logout']);
//        Route::get('profile',               ['uses' => 'UserController@profile',                            'as' => 'profile']);
//        Route::post('address',              ['uses' => 'UserController@address',                            'as' => 'add_address']);
//        Route::post('{id}/update',          ['uses' => 'UserController@update',                             'as' => 'update']);

    });

    // Auth Routes

    Route::group(['prefix' => 'password','as' => 'password.'],function(){

        Route::get('email',                 ['uses' => 'Auth\ForgotPasswordController@showLinkRequestForm', 'as' => 'email']);
        Route::post('email',                ['uses' => 'Auth\ForgotPasswordController@sendResetLinkEmail',  'as' => 'email']);
        Route::get('reset/{token}',         ['uses' => 'Auth\ResetPasswordController@showResetForm',        'as' => 'reset']);
        Route::post('reset',                ['uses' => 'Auth\ResetPasswordController@reset',                'as' => 'reset']);
    });

});

// Rotas do Admin

Route::group(['prefix' => 'admin','as' => 'admin.'],function(){

    // Rotas de Login

    Route::get('login',                 ['uses' => 'Admin\AuthController@index',            'as' => 'login']);
    Route::post('login',                ['uses' => 'Admin\AuthController@login',            'as' => 'login']);


    Route::group(['middleware' => ['orders','admin']],function(){

        // Logout

        Route::get('logout',                ['uses' => 'Admin\AuthController@logout',               'as' => 'logout']);

        // Profile

        Route::get('profile',               ['uses' => 'Admin\AdminController@profile',             'as' => 'profile']);
        Route::post('profile',              ['uses' => 'Admin\AdminController@update_profile',      'as' => 'profile']);

        // Rota Principal

        Route::get('',                      ['uses' => 'Admin\HomeController@index',        'as' => 'index']);

        // Rota Produtos

        Route::group(['prefix' => 'product','as' => 'product.'],function(){

            Route::get('/',                 ['uses' => 'Admin\ProductController@index',         'as' => 'index']);
            Route::get('create',            ['uses' => 'Admin\ProductController@create',        'as' => 'create']);
            Route::post('store',            ['uses' => 'Admin\ProductController@store',         'as' => 'store']);
            Route::get('{id}/edit',         ['uses' => 'Admin\ProductController@edit',          'as' => 'edit']);
            Route::put('{id}',              ['uses' => 'Admin\ProductController@update',        'as' => 'update']);
            Route::delete('{id}',           ['uses' => 'Admin\ProductController@destroy',       'as' => 'destroy']);
        });

        // Rota Categorias

        Route::group(['prefix' => 'category','as' => 'category.'],function(){

            Route::get('/',                 ['uses' => 'Admin\CategoryController@index',    'as' => 'index']);
            Route::get('create',            ['uses' => 'Admin\CategoryController@create',   'as' => 'create']);
            Route::post('store',            ['uses' => 'Admin\CategoryController@store',    'as' => 'store']);
            Route::get('{id}/edit',         ['uses' => 'Admin\CategoryController@edit',     'as' => 'edit']);
            Route::delete('{id}',           ['uses' => 'Admin\CategoryController@destroy',  'as' => 'destroy']);
            Route::put('{id}',              ['uses' => 'Admin\CategoryController@update',   'as' => 'update']);
        });

        // Rota Clientes

        Route::group(['prefix' => 'user','as' => 'user.'],function() {
            Route::get('/',             ['uses' => 'Admin\UserController@index',    'as' => 'index']);
            Route::post('store',        ['uses' => 'Admin\UserController@store',    'as' => 'store']);
            Route::get('/{id}/edit',    ['uses' => 'Admin\UserController@edit',     'as' => 'edit']);
            Route::get('create',        ['uses' => 'Admin\UserController@create',   'as' => 'create']);
            Route::get('export',        ['uses' => 'Admin\UserController@export',   'as' => 'export']);
        });

        // Rota Pedidos

        Route::group(['prefix' => 'order','as' => 'order.'],function(){

            Route::get('/',                 ['uses' => 'Admin\OrderController@index',                   'as' => 'index']);
            Route::get('/create',           ['uses' => 'Admin\OrderController@create',                  'as' => 'create']);
            Route::post('/check',           ['uses' => 'Admin\OrderController@check',                   'as' => 'check']);
            Route::get('/{id}',             ['uses' => 'Admin\OrderController@show',                    'as' => 'show']);
            Route::put('/{id}',             ['uses' => 'Admin\OrderController@update',                  'as' => 'update']);
            Route::get('/{id}/{status}',    ['uses' => 'Admin\OrderController@update_order_status',     'as' => 'update_order_status']);
        });

        // Rota Entrega

resources/views/includes/_errors.blade.php
@if(isset($errors))
    @unless($errors->isEmpty())
        <ol class="msgerro">
            @foreach($errors->getMessages() as $error)
                <li><i class="fa fa-times-circle"></i> {{ $error[0] }}</li>
            @endforeach
        </ol>
    @endunless
@endif
@if(session()->has('success'))
    <ol class="msgsucesso">
        <li>
            <i class="fa fa-check-circle"></i>
            {{ session()->get('success') }}
        </li>
    </ol>
@endif
@if(session()->has('error'))
    <ol class="msgerro">
        <li><i class="fa fa-times-circle"></i> {{ session()->get('error') }}</li>
    </ol>
@endif
@if(session()->has('status'))
    <ol class="msgsucesso">
        <li>
            <i class="fa fa-check-circle"></i>
            {{ session()->get('status') }}
        </li>
    </ol>
@endif

resources/views/includes/_footer.blade.php
<footer class="margin-default-top">
	<div class="wrap">
		<ul class="margin-default-right hide-smartphone">
			<li><img src="../assets/img/img-logo.png" alt=""></li>
		</ul>
		<ul class="margin-default-right display-smartphone-block text-smartphone-center">
			<li>
				<i class="ti-location-pin"></i>
				R. Janúncio Ferreira, 192
			</li>
			<li>
				<i class="ti-email"></i>
				<a href="">texasburgercg@gmail.com</a>
			</li>
			<li>
				<i class="ti-headphone-alt"></i>
				(83) 3341-6153
			</li>
			<li>
				<i class="ti-link"></i>
				<a href="http://texashamburgeria.com.br">texashamburgeria.com.br</a>
			</li>
		</ul>
		<ul class="display-smartphone-block text-smartphone-center">
			<li>Nossas redes</li>
			<li>
				<i class="ti-facebook"></i>
				<a href="https://facebook.com/TexasHA">facebook.com/TexasHA</a>
			</li>
			<li>
				<i class="ti-instagram"></i>
				<a href="https://instagram.com/texas_hamburgueria">@texas_hamburgueria</a>
			</li>
		</ul>
		<ul class="text-right float-right display-smartphone-block text-smartphone-center copy">
			<li>&copy; 2017 Texas Hamburgeria <br/>Todos os direitos reservados</li>
		</ul>
	</div>
</footer>
<script src="{{ asset('assets/js/jquery-2.1.1.min.js') }}"></script>
<script src="{{ asset('assets/js/wow.min.js') }}"></script>
<script src="{{ asset('assets/js/functions.js') }}"></script>
<script src="{{ asset('assets/js/page/product.js') }}"></script>
@if(isset($scripts))
	@foreach($scripts as $script)
		<script src="{{ $script }}"></script>
	@endforeach
@endif

resources/views/includes/_head.blade.php
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width,maximum-scale=1,initial-scale=1,userscalabe=no">
<title>Texas Hamburgeria</title>
<link href="https://fonts.googleapis.com/css?family=Bangers|Patua+One|Rye" rel="stylesheet">
<link rel="stylesheet" href="{{ asset('assets/css/style.css') }}">

@if(isset($stylesheets))
	@foreach($stylesheets as $stylesheet)
		<link rel="stylesheet" href="{{ $stylesheet }}">
	@endforeach
@endif

resources/views/includes/_header.blade.php
{{ Form::hidden('base_url',url()->to('/'),['id' => 'base_url']) }}
{{ Form::hidden('current_url',request()->segment(1),['id' => 'current_url']) }}
<header class="products">
	<div class="wrap row text-left">
		<ul class="col-6">
			<li>
				<a href="../" class="logo">
					<img src="{{ asset('assets/img/img-logo.png') }}" alt="">
				</a>
			</li>
			<li>
				<a class="voltar" href="{{ route('product.index') }}"><i class="pe-is-f-burger-2"></i> <span class="hide-smartphone">Ver</span> <span class="bt-vercardapio">cardápio</span></a>
			</li>
		</ul>
		<ul class="col-6 text-right float-right">
			<li>
				<!-- Botão carrinho -->
				<a class="nohover bt-cart-info" id="bt-cart-info-header" data-cart-count="{{ \Cart::count() }}"><i class="ti-shopping-cart"></i>
					(<span>{{ \Cart::count() }}</span>) <strong class="hide-smartphone">Itens no carrinho</strong>
				</a>
				<!-- Items no carrinho -->
				<div class="cart-items">
					<ul>
						@foreach(Cart::all() as $item)
						<li data-raw-id="{{ session()->has('product_raw_id_' . $item->id) ? session()->get('product_raw_id_' . $item->id) : '' }}" data-product-id="{{ $item->id }}">
							<b>
								<small class="bt-product-remove ti-minus"> </small>
								{{ $item->qty }}
								<small class="bt-product-add ti-plus"> </small>
							</b>
							<strong>
								{{ $item->name }}
								<span>R$ {{ number_format($item->total,2,',','') }}</span>
							</strong>
						</li>
						@endforeach
					</ul>
					<div class="taxa">
						Taxa de entrega
						<span>R$ {{ number_format(request()->instance()->query('delivery_fee'),2,',','') }}</span>
					</div>
					<div class="subtotal">
						Subtotal
						<span>R$ {{ number_format(request()->instance()->query('total'),2,',','') }}</span>
					</div>
					<a href="{{ route('order.index') }}" class="button display-block">Finalizar</a>
				</div>
			</li>
			<!-- USUÁRIO LOGADO POPOVER -->
			@if(Auth::check())
			<li>
				<!-- Botao usuario -->
				<a class="bt-user-info nohover">
					<i class="ti-user"></i> <span class="hide-smartphone">{{ Auth::user()->name }}</span> <i class="ti-angle-down"></i>
				</a>
				<!-- Menu do usuario logado -->
				<div class="user-items">
					<ul>
						<li>
							<a href="{{ route('product.index') }}"><i class="pe-is-f-burger-2"></i> Cardápio</a>
						</li>
						<li>
							<a href="{{ route('user.profile') }}"><i class="ti-settings"></i> Meus dados</a>
						</li>
						<li>
							<a href="{{ route('order.history') }}"><i class="ti-list"></i> Meus pedidos</a>
						</li>
						<li>
							<a href="{{ route('user.logout') }}"><i class="ti-power-off"></i> Sair</a>
						</li>
					</ul>
				</div>
			</li>
			@else
			<!-- USUÁRIO DESLOGADO -->
			<li>
				<a class="login" href="{{ route('user.login.form') }}">
					Entrar / Cadastrar
				</a>
			</li>
			@endif
		</ul>
	</div>
</header>

resources/views/includes/_header_home.blade.php
<header>
    <div class="wrap text-center">
        <div class="logomobile">
            <img src="{{ asset('assets/img/img-logo.png') }}" alt="">
        </div>
        <div class="navmobile">
            <span> </span>
        </div>
        <ul>
            <li class="subheader row ">
                <div class="col-6">
                    <span><i class="ti-headphone-alt"></i> (83) 3341-6153</span>
                    <span><i class="ti-email"></i> texasburgercg@gmail.com</span>
                </div>
                <div class="col-6 text-right">
					<span>
						<i class="ti-timer"></i>
						de Terça à Domingo das 17:00 às 00:00
					</span>
                </div>
            </li>
            <li data-wow-delay="0.9s"><a class="home" href="#inicio">Início</a></li>
            <li data-wow-delay="0.6s"><a href="#destaques">Destaques</a></li>
            <li data-wow-delay="0.3s"><a href='#sobre'>Sobre nós</a></li>
            <li class="logoparent hide-smartphone">
				<span class="logo">
					<img src="{{ asset('assets/img/img-logo.png') }}" alt="">
				</span>
            </li>
            <li data-wow-delay="0.3s"><a href="#delivery">Delivery</a></li>
            <li data-wow-delay="0.6s"><a href="#contato">Contato</a></li>
            <li data-wow-delay="0.9s"><a href="#insta">Instagram</a></li>
        </ul>
    </div>
</header>