routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

//Route::get('/',             ['as' => 'home',        'uses' => 'HomeController@index']);
//Route::get('/login',        ['as' => 'login',       'uses' => 'LoginController@index']);
//Route::get('/menu',         ['as' => 'menu',        'uses' => 'MenuController@index']);
//Route::get('/order',        ['as' => 'order',       'uses' => 'OrderController@index']);
//Route::get('/orders',       ['as' => 'orders',      'uses' => 'OrderController@orders']);
//Route::get('/user',         ['as' => 'user',        'uses' => 'UserController@orders']);


// Rotas da Api

Route::group(['prefix' => 'api','as' => 'api.','middleware' => ['api']],function(){

    Route::group(['prefix' => 'cart','as' => 'cart.'],function(){

        Route::post('add',              ['uses' => 'Api\CartController@add',            'as' => 'add']);
        Route::post('del',              ['uses' => 'Api\CartController@del',            'as' => 'del']);
    });
});

// Rotas do Site

Route::group(['middleware' => ['cart']],function(){

    Route::get('/',['uses' => 'HomeController@index', 'as' => 'index']);

    Route::get('/home',function(){

        return redirect()->route('index');
    });

    Route::get('/login',function(){

        return redirect()->route('user.login.form');
    });

    Route::get('/logout',function(){

        return redirect()->route('user.logout');
    });

    // Products

    Route::group(['prefix' => 'product','as' => 'product.'],function(){

        Route::get('/',                     ['uses' => 'ProductController@index',           'as' => 'index']);
    });

    Route::group(['prefix' => 'order','as' => 'order.','middleware' => 'auth'],function(){

        Route::get('/',                     ['uses' => 'OrderController@index',             'as' => 'index']);
        Route::post('store',                ['uses' => 'OrderController@store',             'as' => 'store']);
        Route::get('history',               ['uses' => 'OrderController@history',           'as' => 'history']);
        Route::get('{id}',                  ['uses' => 'OrderController@show',              'as' => 'show']);
    });

    Route::group(['prefix' => 'user','as' => 'user.'],function(){

        Route::group(['prefix' => 'login','as' => 'login.'],function(){

            Route::get('/',                 ['uses' => 'UserController@login',                              'as' => 'form']);
            Route::post('/',                ['uses' => 'UserController@verify',                             'as' => 'verify']);
        });

        Route::post('store',                ['uses' => 'UserController@store',                              'as' => 'store']);
        Route::get('logout',                ['uses' => 'UserController@logout',                             'as' => 'logout']);
        Route::get('profile',               ['uses' => 'UserController@profile',                            'as' => 'profile']);
        Route::post('address',              ['uses' => 'UserController@address',                            'as' => 'add_address']);
        Route::post('{id}/update',          ['uses' => 'UserController@update',                             'as' => 'update']);

//        Route::group(['prefix' => 'user','as' => 'user.'],function(){
//
//            Route::get('siginup',               ['uses' => 'UserController@create',                             'as' => 'create']);
//            Route::post('siginup',              ['uses' => 'UserController@store',                              'as' => 'store']);
//            Route::post('login',                ['uses' => 'UserController@login',                              'as' => 'login']);
//            Route::get('logout',                ['uses' => 'UserController@logout',                             'as' => 'logout']);
//            Route::get('profile',               ['uses' => 'UserController@profile',                            'as' => 'profile']);
//            Route::post('address',              ['uses' => 'UserController@address',                            'as' => 'add_address']);
//            Route::post('{id}/update',          ['uses' => 'UserController@update',                             'as' => 'update']);
//
//        });



//        Route::post('siginup',              ['uses' => 'UserController@store',                              'as' => 'store']);
//
//        Route::get('logout',                ['uses' => 'UserController@logout',                             'as' => 'logout']);
//        Route::get('profile',               ['uses' => 'UserController@profile',                            'as' => 'profile']);
//        Route::post('address',              ['uses' => 'UserController@address',                            'as' => 'add_address']);
//        Route::post('{id}/update',          ['uses' => 'UserController@update',                             'as' => 'update']);

    });

    // Auth Routes

    Route::group(['prefix' => 'password','as' => 'password.'],function(){

        Route::get('email',                 ['uses' => 'Auth\ForgotPasswordController@showLinkRequestForm', 'as' => 'email']);
        Route::post('email',                ['uses' => 'Auth\ForgotPasswordController@sendResetLinkEmail',  'as' => 'email']);
        Route::get('reset/{token}',         ['uses' => 'Auth\ResetPasswordController@showResetForm',        'as' => 'reset']);
        Route::post('reset',                ['uses' => 'Auth\ResetPasswordController@reset',                'as' => 'reset']);
    });

});

// Rotas do Admin

Route::group(['prefix' => 'admin','as' => 'admin.'],function(){

    // Rotas de Login

    Route::get('login',                 ['uses' => 'Admin\AuthController@index',            'as' => 'login']);
    Route::post('login',                ['uses' => 'Admin\AuthController@login',            'as' => 'login']);


    Route::group(['middleware' => ['orders','admin']],function(){

        // Logout

        Route::get('logout',                ['uses' => 'Admin\AuthController@logout',               'as' => 'logout']);

        // Profile

        Route::get('profile',               ['uses' => 'Admin\AdminController@profile',             'as' => 'profile']);
        Route::post('profile',              ['uses' => 'Admin\AdminController@update_profile',      'as' => 'profile']);

        // Rota Principal

        Route::get('',                      ['uses' => 'Admin\HomeController@index',        'as' => 'index']);

        // Rota Produtos

        Route::group(['prefix' => 'product','as' => 'product.'],function(){

            Route::get('/',                 ['uses' => 'Admin\ProductController@index',         'as' => 'index']);
            Route::get('create',            ['uses' => 'Admin\ProductController@create',        'as' => 'create']);
            Route::post('store',            ['uses' => 'Admin\ProductController@store',         'as' => 'store']);
            Route::get('{id}/edit',         ['uses' => 'Admin\ProductController@edit',          'as' => 'edit']);
            Route::put('{id}',              ['uses' => 'Admin\ProductController@update',        'as' => 'update']);
            Route::delete('{id}',           ['uses' => 'Admin\ProductController@destroy',       'as' => 'destroy']);
        });

        // Rota Categorias

        Route::group(['prefix' => 'category','as' => 'category.'],function(){

            Route::get('/',                 ['uses' => 'Admin\CategoryController@index',    'as' => 'index']);
            Route::get('create',            ['uses' => 'Admin\CategoryController@create',   'as' => 'create']);
            Route::post('store',            ['uses' => 'Admin\CategoryController@store',    'as' => 'store']);
            Route::get('{id}/edit',         ['uses' => 'Admin\CategoryController@edit',     'as' => 'edit']);
            Route::delete('{id}',           ['uses' => 'Admin\CategoryController@destroy',  'as' => 'destroy']);
            Route::put('{id}',              ['uses' => 'Admin\CategoryController@update',   'as' => 'update']);
        });

        // Rota Clientes

        Route::group(['prefix' => 'user','as' => 'user.'],function() {
            Route::get('/',             ['uses' => 'Admin\UserController@index',    'as' => 'index']);
            Route::post('store',        ['uses' => 'Admin\UserController@store',    'as' => 'store']);
            Route::get('/{id}/edit',    ['uses' => 'Admin\UserController@edit',     'as' => 'edit']);
            Route::get('create',        ['uses' => 'Admin\UserController@create',   'as' => 'create']);
            Route::get('export',        ['uses' => 'Admin\UserController@export',   'as' => 'export']);
        });

        // Rota Pedidos

        Route::group(['prefix' => 'order','as' => 'order.'],function(){

            Route::get('/',                 ['uses' => 'Admin\OrderController@index',                   'as' => 'index']);
            Route::get('/create',           ['uses' => 'Admin\OrderController@create',                  'as' => 'create']);
            Route::post('/check',           ['uses' => 'Admin\OrderController@check',                   'as' => 'check']);
            Route::get('/{id}',             ['uses' => 'Admin\OrderController@show',                    'as' => 'show']);
            Route::put('/{id}',             ['uses' => 'Admin\OrderController@update',                  'as' => 'update']);
            Route::get('/{id}/{status}',    ['uses' => 'Admin\OrderController@update_order_status',     'as' => 'update_order_status']);
        });

        // Rota Entrega

app/User.php
<?php

namespace App;

use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;
    use SoftDeletes;

    protected $dates = [

        'created_at',
        'updated_at',
        'deleted_at'
    ];
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = ['name', 'email','phone','birthday','password'];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function addresses(){

        return $this->hasMany('App\UserAddress');
    }

    public function address(){

        return $this->hasOne('App\UserAddress')->where('default', 1);
    }

    public function orders(){

        return $this->hasMany('App\Order');
    }

    public function sendPasswordResetNotification($token)
    {
        $this->notify(new ResetPasswordNotification($token));
    }
}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Services\UserService;
use App\User;
use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Validator;

class UserController extends Controller
{

    private $user_service;

    public function __construct()
    {

        $this->user_service = new UserService();
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

    public function index(Request $request)
    {

        $scripts = [

            asset('assets/admin/js/page/user.js')
        ];

        $data = $request->all();
        $users = $this->user_service->get_users($data);

        return view('admin.user.index')
            ->with('users',$users)
            ->with('title', 'Usuários')
            ->with('scripts',$scripts);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {

        $scripts = [

            asset('assets/plugins/jquery-mask/jquery.mask.min.js'),
            asset('assets/admin/js/page/user.create.js')
        ];

        $states = \Helper::states();

        return view('admin.user.create')
            ->with('scripts',$scripts)
            ->with('states',$states);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        try{

            $validator = Validator::make($request->all(), [

                'name'                      => 'required|min:5|max:100',
                'email'                     => 'required|email|unique:users',
                'phone'                     => 'required|min:14|max:15',
                'zipcode'                   => 'required|min:10|max:10',
                'district'                  => 'required|max:50',
                'address'                   => 'required|max:100',
                'number'                    => 'required|max:20',
                'complement'                => 'max:50',
                'city'                      => 'required|max:100',
                'state'                     => 'required'

            ]);

            if ($validator->fails()) {

                return redirect()
                    ->back()
                    ->withErrors($validator)
                    ->withInput();
            }

            $data = $request->all();
            $data['password'] = \Helper::generate_password();
            $user_store_response = $this->user_service->store($data);

            if($user_store_response['error']){

                return redirect()->back()->with('error',$user_store_response['msg']);
            }

            return redirect()->route('admin.user.index');
        }
        catch (Exception $e){

            return redirect()->back()->with('error',$e->getMessage());
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {

        $states = \Helper::states();

        $scripts = [

            asset('assets/plugins/jquery-mask/jquery.mask.min.js'),
            asset('assets/admin/js/page/user.edit.js')
        ];

        $user = User::find($id);

        if(!$user){

            return redirect()->back()->with('error','Usuário não encontrado');
        }

        return view('admin.user.edit')
            ->with('user',$user)
            ->with('states',$states)
            ->with('scripts',$scripts);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    public function export()
    {
        $headers = array(
            "Content-type" => "text/csv",
            "Content-Disposition" => "attachment; filename=emails-" . time() . ".csv",
            "Pragma" => "no-cache",
            "Cache-Control" => "must-revalidate, post-check=0, pre-check=0",
            "Expires" => "0"
        );
        $callback = $this->user_service->export();
        return response()->stream($callback, 200, $headers);
    }
}

resources/views/admin/user/create.blade.php
@extends('admin.layout')
@section('content')
	<!-- cadastrar cliente - inicio -->
	<div class="limite content">
		<section class="form">
			<h2 class="clearfix">
				<i class="fa fa-group styled"></i>
				Adicionar cliente
			</h2>
			<div class="box meusdados">
				@include('includes._errors')
				{{ Form::open(['route' => 'admin.user.store','method' => 'POST']) }}
				<ul>
					<li>
						{{ Form::label('Nome') }}
						{{ Form::text('name',null,['placeholder' => 'Inserir nome']) }}
					</li>
					<li>
						{{ Form::label('E-mail') }}
						{{ Form::text('email',null,['placeholder' => 'Inserir e-mail do cliente']) }}
					</li>
					<li>
						{{ Form::label('Telefone') }}
						{{ Form::text('phone',null,['placeholder' => 'Inserir telefone do cliente','class' => 'phone']) }}
					</li>
					<li>
						{{ Form::label('Data de nascimento') }}
						{{ Form::text('birthday',null,['placeholder' => 'DD/MM/AAAA','class' => 'date']) }}
					</li>
				</ul>
				<ul>
					<li>
						{{ Form::label('CEP') }}
						{{ Form::text('zipcode',null,['placeholder' => 'Digite o CEP','class' => 'zipcode','id' => 'zipcode']) }}
					</li>
					<li>
						{{ Form::label('Bairro') }}
						{{ Form::text('district',null,['placeholder' => 'Informe o bairro', 'id' => 'district']) }}
					</li>
					<li>
						{{ Form::label('Endereço') }}
						{{ Form::text('address',null,['placeholder' => 'Ex: Rua do Conde','id' => 'address']) }}
					</li>
					<li class="numero">
						{{ Form::label('Número') }}
						{{ Form::text('number',null,['placeholder' => 'Ex: 1002']) }}
					</li>
					<li class="complemento">
						{{ Form::label('Complemento') }}
						{{ Form::text('complement',null,['placeholder' => 'EX: Apto 203']) }}
					</li>
					<li>
						{{ Form::label('Cidade') }}
						{{ Form::text('city',null,['placeholder' => 'Informe a cidade','id' => 'city']) }}
					</li>
					<li>
						{{ Form::label('Estado') }}
						{{ Form::select('state',$states,null,['placeholder' => 'Selecione o estado','id' => 'state']) }}
					</li>
					<li>
						{{ Form::submit('Adicionar cliente',['class' => 'botao']) }}
						<a href="{{ route('admin.admin.index') }}" class="botao cancel">
							Cancelar
						</a>
					</li>
				</ul>
				{{ Form::close() }}
			</div>
		</section>
	</div>
	<!-- cadastrar cliente- fim -->

	{{--<!-- editar cliente - inicio -->--}}
	{{--<div class="limite content">--}}
		{{--<section class="form">--}}
			{{--<h2 class="clearfix">--}}
				{{--<i class="fa fa-group styled"></i>--}}
				{{--Dados do cliente Raphael--}}
			{{--</h2>--}}

				{{--<a class="botao" href="{{ route('admin.order.create') }}"><i class="fa fa-plus-square-o"></i>Fazer um novo pedido</a>--}}
			{{--<div class="box meusdados">--}}
				{{--<ul>--}}
					{{--<li>--}}
						{{--{{ Form::label('Nome') }}--}}
						{{--{{ Form::text('name',null,['placeholder' => 'Inserir nome']) }}--}}
					{{--</li>--}}
					{{--<li>--}}
						{{--{{ Form::label('E-mail') }}--}}
						{{--{{ Form::text('email',null,['placeholder' => 'Inserir e-mail do cliente']) }}--}}
					{{--</li>--}}
					{{--<li>--}}
						{{--{{ Form::label('Telefone') }}--}}
						{{--{{ Form::text('telefone',null,['placeholder' => 'Inserir telefone do cliente']) }}--}}
					{{--</li>--}}
					{{--<li>--}}
						{{--{{ Form::label('Data de nascimento') }}--}}
						{{--{{ Form::text('nascimento',null,['placeholder' => 'DD/MM/AAAA']) }}--}}
					{{--</li>--}}
					{{--<li>--}}
						{{--{{ Form::label('Senha') }}--}}
						{{--{{ Form::password('senha',null,['placeholder' => 'Insira a senha']) }}--}}
					{{--</li>--}}
					{{--<li>--}}
						{{--{{ Form::label('Confirmar a senha') }}--}}
						{{--{{ Form::password('resenha',null,['placeholder' => 'Insira a senha']) }}--}}
					{{--</li>--}}
				{{--</ul>--}}
				{{--<ul>--}}
					{{--<li>--}}
						{{--{{ Form::label('CEP') }}--}}
						{{--{{ Form::text('cep',null,['placeholder' => 'Digite o CEP']) }}--}}
					{{--</li>--}}
					{{--<li>--}}
						{{--{{ Form::label('Bairro') }}--}}
						{{--{{ Form::text('bairro',null,['placeholder' => 'Informe o bairro']) }}--}}
					{{--</li>--}}
					{{--<li>--}}
						{{--{{ Form::label('Endereço') }}--}}
						{{--{{ Form::text('endereco',null,['placeholder' => 'Ex: Rua do Conde']) }}--}}
					{{--</li>--}}
					{{--<li class="numero">--}}
						{{--{{ Form::label('Número') }}--}}
						{{--{{ Form::text('numero',null,['placeholder' => 'Ex: 1002']) }}--}}
					{{--</li>--}}
					{{--<li class="complemento">--}}
						{{--{{ Form::label('Complemento') }}--}}
						{{--{{ Form::text('complemento',null,['placeholder' => 'EX: Apto 203']) }}--}}
					{{--</li>--}}
					{{--<li>--}}
						{{--{{ Form::label('Cidade') }}--}}
						{{--{{ Form::text('cidade',null,['placeholder' => 'Informe a cidade']) }}--}}
					{{--</li>--}}
					{{--<li>--}}
						{{--{{ Form::label('Estado') }}--}}
						{{--<select name="" id="">--}}
							{{--<option value="">Selecione o estado</option>--}}
						{{--</select>--}}
					{{--</li>--}}
					{{--<li>--}}
						{{--{{ Form::submit('Adicionar cliente',['class' => 'botao']) }}--}}
						{{--<a href="{{ route('admin.admin.index') }}" class="botao cancel">--}}
							{{--Cancelar--}}
						{{--</a>--}}
					{{--</li>--}}
				{{--</ul>--}}
			{{--</div>--}}
		{{--</section>--}}
	{{--</div>--}}
	{{--<!-- editar cliente- fim -->--}}
@endsection

resources/views/admin/user/edit.blade.php
@extends('admin.layout')
@section('content')
    <!-- cadastrar cliente - inicio -->
    <div class="limite content">
        <section class="form">
            <h2 class="clearfix">
                <i class="fa fa-group styled"></i>
                Editar cliente
                <a class="botao menor" href="{{ route('admin.order.create') }}"><i class="fa fa-plus-square-o"></i>Fazer um novo pedido</a>
            </h2>
            <div class="box meusdados">
                @include('includes._errors')
                {{ Form::open(['route' => 'admin.user.store','method' => 'POST']) }}
                <ul>
                    <li>
                        {{ Form::label('Nome') }}
                        {{ Form::text('name',$user->name,['placeholder' => 'Inserir nome']) }}
                    </li>
                    <li>
                        {{ Form::label('E-mail') }}
                        {{ Form::text('email',$user->email,['placeholder' => 'Inserir e-mail do cliente']) }}
                    </li>
                    <li>
                        {{ Form::label('Telefone') }}
                        {{ Form::text('phone',$user->phone,['placeholder' => 'Inserir telefone do cliente','class' => 'phone']) }}
                    </li>
                    <li>
                        {{ Form::label('Data de nascimento') }}
                        {{ Form::text('birthday',Carbon::parse($user->birthday)->format('d/m/Y'),['placeholder' => 'DD/MM/AAAA','class' => 'date']) }}
                    </li>
                </ul>
                <div class="enderecos">
                    <ul>
                        <li>
                            {{ Form::label('CEP') }}
                            {{ Form::text('zipcode',null,['placeholder' => 'Digite o CEP','class' => 'zipcode','id' => 'zipcode']) }}
                        </li>
                        <li>
                            {{ Form::label('Bairro') }}
                            {{ Form::text('district',null,['placeholder' => 'Informe o bairro', 'id' => 'district']) }}
                        </li>
                        <li>
                            {{ Form::label('Endereço') }}
                            {{ Form::text('address',null,['placeholder' => 'Ex: Rua do Conde','id' => 'address']) }}
                        </li>
                        <li class="numero">
                            {{ Form::label('Número') }}
                            {{ Form::text('number',null,['placeholder' => 'Ex: 1002']) }}
                        </li>
                        <li class="complemento">
                            {{ Form::label('Complemento') }}
                            {{ Form::text('complement',null,['placeholder' => 'EX: Apto 203']) }}
                        </li>
                        <li>
                            {{ Form::label('Cidade') }}
                            {{ Form::text('city',null,['placeholder' => 'Informe a cidade','id' => 'city']) }}
                        </li>
                        <li>
                            {{ Form::label('Estado') }}
                            {{ Form::select('state',$states,null,['placeholder' => 'Selecione o estado','id' => 'state']) }}
                        </li>
                        <li>
                            {{ Form::submit('+ Adicionar endereço',['class' => 'botao']) }}
                        </li>
                    </ul>

                    <h1 class="clearfix">Editar endereços</h1>
                    <ul>
                        <li>
                            {{ Form::label('CEP') }}
                            {{ Form::text('zipcode','54430-160',['placeholder' => 'Digite o CEP','class' => 'zipcode','id' => 'zipcode']) }}
                        </li>
                        <li>
                            {{ Form::label('Bairro') }}
                            {{ Form::text('district','Candeias',['placeholder' => 'Informe o bairro', 'id' => 'district']) }}
                        </li>
                        <li>
                            {{ Form::label('Endereço') }}
                            {{ Form::text('address','Rua Amambai',['placeholder' => 'Ex: Rua do Conde','id' => 'address']) }}
                        </li>
                        <li class="numero">
                            {{ Form::label('Número') }}
                            {{ Form::text('number','198',['placeholder' => 'Ex: 1002']) }}
                        </li>
                        <li class="complemento">
                            {{ Form::label('Complemento') }}
                            {{ Form::text('complement','Apto 203',['placeholder' => 'EX: Apto 203']) }}
                        </li>
                        <li>
                            {{ Form::label('Cidade') }}
                            {{ Form::text('city','Jaboatão dos Guararapes',['placeholder' => 'Informe a cidade','id' => 'city']) }}
                        </li>
                        <li>
                            {{ Form::label('Estado') }}
                            {{ Form::select('state',$states,null,['placeholder' => 'Selecione o estado','id' => 'state']) }}
                        </li>
                        <li></li>
                        <li>
                            <button class="f-right botao delete" type="button">Remover endereço</button>
                        </li>
                    </ul>
                </div>
                <ul>
                    <li>
                        {{ Form::submit('Salvar alterações',['class' => 'botao']) }}
                        <a href="{{ route('admin.admin.index') }}" class="botao cancel">
                            Cancelar
                        </a>
                    </li>
                </ul>
                {{ Form::close() }}
            </div>
        </section>
    </div>
@endsection

resources/views/admin/user/index.blade.php
@extends('admin.layout')
@section('content')
<!-- conteúdo -->
<div class="limite content">
	<section class="tabela">
		<h2 class="clearfix">
			<i class="fa fa-users styled"></i>
			Clientes cadastrados

			{{ Form::open(['name' => 'interval_form','method' => 'GET', 'url' => request()->url() ]) }}

			<div class="filter">
				Ordenar por:
				{{ Form::select('interval',['' => 'Mais recentes','old' => 'Mais antigos','alphabetic' => 'Ordem alfabetica'],request()->has('interval') && request()->get('interval') != null ? request()->get('interval') : null) }}
			</div>

			{{ Form::close() }}

			<div class="pesquisa">
				{{ Form::open(['name' => 'search','method' => 'GET', request()->url()]) }}
				{{ Form::text('search',request()->get('search'),['placeholder' => 'Pesquisar']) }}
				{{ Form::close() }}
				<i class="fa fa-search"></i>
			</div>
			<a class="botao menor" href="{{ route('admin.user.export') }}"><i class="fa fa-envelope-o"></i>Download emails</a>
			<a class="botao menor" href="{{ route('admin.user.create') }}"><i class="fa fa-plus-square-o"></i>Adicionar cliente</a>
		</h2>
		<table class="clicavel">
			<thead>
				<th>ID</th>
				<th>Nome</th>
				<th>E-mail</th>
				<th>Telefone</th>
				<th>Pedidos</th>
				<th>Cliente desde</th>
			</thead>
			<tbody>
			@foreach($users as $user)
				<tr data-href='{{ route('admin.user.edit',$user->id) }}' title="Clique para ver os detalhes" title="Clique para ver os detalhes">
					<td>#{{ $user->id }}</td>
					<td>{{ $user->name }}</td>
					<td>{{ $user->email }}</td>
					<td>{{ $user->phone }}</td>
					<td>{{ count($user->orders) }}</td>
					<td>{{ $user->created_at->format('d/m/Y - H:i') }}</td>
				</tr>
			@endforeach
			</tbody>
		</table>
	</section>

	<nav class="pager">
		{{ $users->appends(['status' => request()->get('status'), 'interval' => request()->get('interval'), 'search' => request()->get('search') ])->links() }}
	</nav>
</div>
@endsection